version: '3'

services:
  bam_mongo:
    container_name: bam_mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    env_file:
      - docker-compose.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./server/scripts/initDB.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - bam_app
  bam_server:
    depends_on:
      - bam_mongo
    container_name: bam_server
    build: ../../Desktop/BAM
    ports:
      - "5000:5000"
    networks:
      - bam_app

networks:
  bam_app:
    driver: bridge